// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdd9MkUNuU_06gYjVZEX6rDvVNEK9Qv_I',
    appId: '1:785619130237:android:3f65ff9f248dd13cb5de14',
    messagingSenderId: '785619130237',
    projectId: 'proxima-ride-app-devop',
    storageBucket: 'proxima-ride-app-devop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk_YazOpBL9jGtUNlcLwR0b_0tM1P5z1k',
    appId: '1:785619130237:ios:12ab4eb3ed5b1e7db5de14',
    messagingSenderId: '785619130237',
    projectId: 'proxima-ride-app-devop',
    storageBucket: 'proxima-ride-app-devop.firebasestorage.app',
    androidClientId:
        '785619130237-21qtien4t7pvrkcqned4h3bac7o39qg5.apps.googleusercontent.com',
    iosClientId:
        '785619130237-11kpq56e9sbtu64inc3l5d812h4ad41j.apps.googleusercontent.com',
    iosBundleId: 'com.example.proximaRide',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt3Y5R24dI1V-qArWRVVXwSvrwrvreyf0',
    appId: '1:785619130237:web:20f9ee0f705e60e4b5de14',
    messagingSenderId: '785619130237',
    projectId: 'proxima-ride-app-devop',
    authDomain: 'proxima-ride-app-devop.firebaseapp.com',
    storageBucket: 'proxima-ride-app-devop.firebasestorage.app',
  );
}
