<?php

namespace App\Http\Resources\Admin;

use App\Models\FeaturesSettingDetail;
use Illuminate\Http\Resources\Json\JsonResource;

class FindRidePageSettingDetailResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'find_ride_page_setting_id' => $this->find_ride_page_setting_id,
            'language_id' => $this->language_id,
            'name' => $this->name,
            'meta_keywords' => $this->meta_keywords,
            'meta_description' => $this->meta_description,
            'main_heading' => $this->main_heading,
            'pink_ride_page_heading' => $this->pink_ride_page_heading,
            'extra_care_ride_page_label' => $this->extra_care_ride_page_label,
            'pink_ride_page_label' => $this->pink_ride_page_label,
            'search_results_pink_ride_label' => $this->search_results_pink_ride_label,
            'search_results_extra_care_ride_label' => $this->search_results_extra_care_ride_label,
            'more_rides_pink_ride_label' => $this->more_rides_pink_ride_label,
            'to_pink_ride_label' => $this->to_pink_ride_label,
            'imp_pink_ride_label' => $this->imp_pink_ride_label,
            'imp_extra_care_ride_label' => $this->imp_extra_care_ride_label,
            'navbar_icon' => $this->navbar_icon,
            'from_field_icon' => $this->from_field_icon,
            'swap_field_icon' => $this->swap_field_icon,
            'to_field_icon' => $this->to_field_icon,
            'date_field_icon' => $this->date_field_icon,
            'search_field_icon' => $this->search_field_icon,
            'search_section_from_placeholder' => $this->search_section_from_placeholder,
            'search_section_to_placeholder' => $this->search_section_to_placeholder,
            'search_section_date_placeholder' => $this->search_section_date_placeholder,
            'search_section_required_error' => $this->search_section_required_error,
            'search_section_keyword_label' => $this->search_section_keyword_label,
            'search_section_keyword_placeholder' => $this->search_section_keyword_placeholder,
            'search_section_button_label' => $this->search_section_button_label,
            'search_section_recent_searches' => $this->search_section_recent_searches,
            'card_section_from_label' => $this->card_section_from_label,
            'card_section_to_label' => $this->card_section_to_label,
            'card_section_at_label' => $this->card_section_at_label,
            'card_section_seats_left' => $this->card_section_seats_left,
            'card_section_per_seat' => $this->card_section_per_seat,
            'heading_ride_card_section' => $this->heading_ride_card_section,
            'card_section_booked' => $this->card_section_booked,
            'card_section_seats' => $this->card_section_seats,
            'card_section_booking_fee' => $this->card_section_booking_fee,
            'card_section_seats_fee' => $this->card_section_seats_fee,
            'card_section_amount' => $this->card_section_amount,
            'card_section_driver' => $this->card_section_driver,
            'card_section_age' => $this->card_section_age,
            'card_section_driven' => $this->card_section_driven,
            'card_section_passengers' => $this->card_section_passengers,
            'card_section_review' => $this->card_section_review,
            'card_section_completed' => $this->card_section_completed,
            'trips_card_section_seat_booked' => $this->trips_card_section_seat_booked,
            'trips_card_section_seat_available' => $this->trips_card_section_seat_available,
            'trips_card_section_review_driver' => $this->trips_card_section_review_driver,
            'firm_cancellation_tooltip' => $this->firm_cancellation_tooltip,
            'filter_section_heading' => $this->filter_section_heading,
            'filter1_driver_heading' => $this->filter1_driver_heading,
            'driver_age_label' => $this->driver_age_label,
            'driver_age_placeholder' => $this->driver_age_placeholder,
            'driver_rating_label' => $this->driver_rating_label,
            'driver_rating_placeholder' => $this->driver_rating_placeholder,
            'driver_phone_access_label' => $this->driver_phone_access_label,
            'driver_know_label' => $this->driver_know_label,
            'driver_know_placeholder' => $this->driver_know_placeholder,
            'filter2_passengers_heading' => $this->filter2_passengers_heading,
            'passengers_rating_label' => $this->passengers_rating_label,
            'passengers_rating_placeholder' => $this->passengers_rating_placeholder,
            'filter3_payment_methods_heading' => $this->filter3_payment_methods_heading,
            'clear_button_label' => $this->clear_button_label,
            'apply_button_label' => $this->apply_button_label,
            'card_section_no_review' => $this->card_section_no_review,
            'payment_methods_label' => $this->payment_methods_label,
            'search_section_pink_ride_label' => $this->search_section_pink_ride_label,
            'search_section_extra_care_label' => $this->search_section_extra_care_label,
            'payment_methods_option4' => FeaturesSettingDetail::whereFeaturesSettingId($this->payment_methods_option4)->whereLanguageId($this->language_id)->value('name'),
            'payment_methods_option2' => FeaturesSettingDetail::whereFeaturesSettingId($this->payment_methods_option2)->whereLanguageId($this->language_id)->value('name'),
            'payment_methods_option3' => FeaturesSettingDetail::whereFeaturesSettingId($this->payment_methods_option3)->whereLanguageId($this->language_id)->value('name'),
            'payment_methods_option1' => $this->payment_methods_option1,
            'filter4_vehicle_heading' => $this->filter4_vehicle_heading,
            'vehicle_type_label' => $this->vehicle_type_label,
            'vehicle_type_placeholder' => $this->vehicle_type_placeholder,
            'ride_features_option1' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option1)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option2' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option2)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option3' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option3)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option4' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option4)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option5' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option5)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option6' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option6)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option7' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option7)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option8' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option8)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option9' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option9)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option10' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option10)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option11' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option11)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option12' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option12)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option13' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option13)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option14' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option14)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option15' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option15)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option16' => FeaturesSettingDetail::whereFeaturesSettingId($this->ride_features_option16)->whereLanguageId($this->language_id)->value('name'),
            'ride_features_option17' => $this->ride_features_option17,
            'luggage_label' => $this->luggage_label,
            'luggage_placeholder' => $this->luggage_placeholder,
            'smoking_label' => $this->smoking_label,
            'search_result_load_more_btn' => $this->search_result_load_more_btn,
            'search_result_no_more_data_message' => $this->search_result_no_more_data_message,
            'search_result_no_found_message' => $this->search_result_no_found_message,
            'search_result_label' => $this->search_result_label,
            'filter_what_label' => $this->filter_what_label,
            'search_and_above_label' => $this->search_and_above_label,
            'search_filter_all_label' => $this->search_filter_all_label,
            'search_filter_select_vehicle_label' => $this->search_filter_select_vehicle_label,
            'card_section_not_live' => $this->card_section_not_live,
            'card_section_booking_request' => $this->card_section_booking_request,
            'trips_card_section_reviewed' => $this->trips_card_section_reviewed,
            'filter_search_btn_label' => $this->filter_search_btn_label,
            'filter_close_btn_label' => $this->filter_close_btn_label,
            'ride_preferences_label' => $this->ride_preferences_label,
            'hide_ride_popup_heading' => $this->hide_ride_popup_heading,
            'hide_ride_popup_text' => $this->hide_ride_popup_text,
            'hide_ride_popup_confirm_button' => $this->hide_ride_popup_confirm_button,
            'hide_ride_popup_take_me_back_button' => $this->hide_ride_popup_take_me_back_button,
            'smoking_option1' => FeaturesSettingDetail::whereFeaturesSettingId($this->smoking_option1)->whereLanguageId($this->language_id)->value('name'),
            'smoking_option2' => FeaturesSettingDetail::whereFeaturesSettingId($this->smoking_option2)->whereLanguageId($this->language_id)->value('name'),
            'pets_allowed_label' => $this->pets_allowed_label,
            'pets_allowed_option1' => FeaturesSettingDetail::whereFeaturesSettingId($this->pets_allowed_option1)->whereLanguageId($this->language_id)->value('name'),
            'pets_allowed_option2' => FeaturesSettingDetail::whereFeaturesSettingId($this->pets_allowed_option2)->whereLanguageId($this->language_id)->value('name'),
            'pets_allowed_option3' => FeaturesSettingDetail::whereFeaturesSettingId($this->pets_allowed_option3)->whereLanguageId($this->language_id)->value('name'),
            'card_section_cancelled' => $this->card_section_cancelled,
            'find_ride_page_setting' => new FindRidePageSettingResource($this->whenLoaded('findRidePageSetting')),
            'language' => new LanguageResource($this->whenLoaded('language')),
        ];
    }
}
