<?php

namespace App\Http\Resources\Admin;

use Illuminate\Http\Resources\Json\JsonResource;

class HomePageSettingDetailResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'home_page_setting_id' => $this->home_page_setting_id,
            'language_id' => $this->language_id,
            'name' => $this->name,
            'meta_keywords' => $this->meta_keywords,
            'meta_description' => $this->meta_description,
            'slider_heading' => $this->slider_heading,
            'slider_from_placeholder' => $this->slider_from_placeholder,
            'slider_to_placeholder' => $this->slider_to_placeholder,
            'slider_date_placeholder' => $this->slider_date_placeholder,
            'slider_required_error' => $this->slider_required_error,
            'slider_image' => $this->slider_image,
            'from_field_icon' => $this->from_field_icon,
            'swap_field_icon' => $this->swap_field_icon,
            'to_field_icon' => $this->to_field_icon,
            'date_field_icon' => $this->date_field_icon,
            'search_field_icon' => $this->search_field_icon,
            'section1_main_heading' => $this->section1_main_heading,
            'section1_pink_rides_label' => $this->section1_pink_rides_label,
            'section1_pink_rides_image' => $this->section1_pink_rides_image,
            'section1_pink_rides_description' => $this->section1_pink_rides_description,
            'section1_folks_rides_label' => $this->section1_folks_rides_label,
            'section1_folks_rides_image' => $this->section1_folks_rides_image,
            'section1_folks_rides_description' => $this->section1_folks_rides_description,
            'section1_customize_label' => $this->section1_customize_label,
            'section1_customize_image' => $this->section1_customize_image,
            'section1_customize_description' => $this->section1_customize_description,
            'section2_main_heading' => $this->section2_main_heading,
            'section2_profile_verification_label' => $this->section2_profile_verification_label,
            'section2_profile_verification_image' => $this->section2_profile_verification_image,
            'section2_profile_verification_description' => $this->section2_profile_verification_description,
            'section2_policies_label' => $this->section2_policies_label,
            'section2_policies_image' => $this->section2_policies_image,
            'section2_policies_description' => $this->section2_policies_description,
            'section2_car_insurance_label' => $this->section2_car_insurance_label,
            'section2_car_insurance_image' => $this->section2_car_insurance_image,
            'section2_car_insurance_description' => $this->section2_car_insurance_description,
            'section2_help_label' => $this->section2_help_label,
            'section2_help_image' => $this->section2_help_image,
            'section2_help_description' => $this->section2_help_description,
            'section3_main_heading' => $this->section3_main_heading,
            'section3_safe_label' => $this->section3_safe_label,
            'section3_safe_image' => $this->section3_safe_image,
            'section3_safe_description' => $this->section3_safe_description,
            'section3_affordable_label' => $this->section3_affordable_label,
            'section3_affordable_image' => $this->section3_affordable_image,
            'section3_affordable_description' => $this->section3_affordable_description,
            'section3_reliable_label' => $this->section3_reliable_label,
            'section3_reliable_image' => $this->section3_reliable_image,
            'section3_reliable_description' => $this->section3_reliable_description,
            'section4_main_heading' => $this->section4_main_heading,
            'work_section_main_heading' => $this->work_section_main_heading,
            'work_section_main_text' => $this->work_section_main_text,
            'work_section_passenger_label' => $this->work_section_passenger_label,
            'work_section_passenger_description' => $this->work_section_passenger_description,
            'work_section_passenger_point1_label' => $this->work_section_passenger_point1_label,
            'work_section_passenger_point1_image' => $this->work_section_passenger_point1_image,
            'work_section_passenger_point1_description' => $this->work_section_passenger_point1_description,
            'work_section_passenger_point2_label' => $this->work_section_passenger_point2_label,
            'work_section_passenger_point2_image' => $this->work_section_passenger_point2_image,
            'work_section_passenger_point2_description' => $this->work_section_passenger_point2_description,
            'work_section_passenger_point3_label' => $this->work_section_passenger_point3_label,
            'work_section_passenger_point3_image' => $this->work_section_passenger_point3_image,
            'work_section_passenger_point3_description' => $this->work_section_passenger_point3_description,
            'work_section_passenger_point4_label' => $this->work_section_passenger_point4_label,
            'work_section_passenger_point4_image' => $this->work_section_passenger_point4_image,
            'work_section_passenger_point4_description' => $this->work_section_passenger_point4_description,
            'work_section_passenger_point5_label' => $this->work_section_passenger_point5_label,
            'work_section_passenger_point5_image' => $this->work_section_passenger_point5_image,
            'work_section_passenger_point5_description' => $this->work_section_passenger_point5_description,
            'work_section_driver_label' => $this->work_section_driver_label,
            'work_section_driver_description' => $this->work_section_driver_description,
            'work_section_driver_point1_label' => $this->work_section_driver_point1_label,
            'work_section_driver_point1_image' => $this->work_section_driver_point1_image,
            'work_section_driver_point1_description' => $this->work_section_driver_point1_description,
            'work_section_driver_point2_label' => $this->work_section_driver_point2_label,
            'work_section_driver_point2_image' => $this->work_section_driver_point2_image,
            'work_section_driver_point2_description' => $this->work_section_driver_point2_description,
            'work_section_driver_point3_label' => $this->work_section_driver_point3_label,
            'work_section_driver_point3_image' => $this->work_section_driver_point3_image,
            'work_section_driver_point3_description' => $this->work_section_driver_point3_description,
            'work_section_driver_point4_label' => $this->work_section_driver_point4_label,
            'work_section_driver_point4_image' => $this->work_section_driver_point4_image,
            'work_section_driver_point4_description' => $this->work_section_driver_point4_description,
            'work_section_driver_point5_label' => $this->work_section_driver_point5_label,
            'work_section_driver_point5_image' => $this->work_section_driver_point5_image,
            'work_section_driver_point5_description' => $this->work_section_driver_point5_description,
            'doing_section_main_heading' => $this->doing_section_main_heading,
            'doing_section_main_text' => $this->doing_section_main_text,
            'doing_section_slider_image' => $this->doing_section_slider_image,
            'doing_section_label1' => $this->doing_section_label1,
            'doing_section_label2' => $this->doing_section_label2,
            'reasons_section_main_heading' => $this->reasons_section_main_heading,
            'reasons_section_main_text' => $this->reasons_section_main_text,
            'reasons_section_members_label' => $this->reasons_section_members_label,
            'reasons_section_members_image' => $this->reasons_section_members_image,
            'reasons_section_members_description' => $this->reasons_section_members_description,
            'reasons_section_driver_label' => $this->reasons_section_driver_label,
            'reasons_section_driver_image' => $this->reasons_section_driver_image,
            'reasons_section_driver_description' => $this->reasons_section_driver_description,
            'reasons_section_quality_label' => $this->reasons_section_quality_label,
            'reasons_section_quality_image' => $this->reasons_section_quality_image,
            'reasons_section_quality_description' => $this->reasons_section_quality_description,
            'reasons_section_policy_label' => $this->reasons_section_policy_label,
            'reasons_section_policy_image' => $this->reasons_section_policy_image,
            'reasons_section_policy_description' => $this->reasons_section_policy_description,
            'reasons_section_students_label' => $this->reasons_section_students_label,
            'reasons_section_students_image' => $this->reasons_section_students_image,
            'reasons_section_students_description' => $this->reasons_section_students_description,
            'reasons_section_safety_label' => $this->reasons_section_safety_label,
            'reasons_section_safety_image' => $this->reasons_section_safety_image,
            'reasons_section_safety_description' => $this->reasons_section_safety_description,
            'reasons_section_price_label' => $this->reasons_section_price_label,
            'reasons_section_price_image' => $this->reasons_section_price_image,
            'reasons_section_price_description' => $this->reasons_section_price_description,
            'reasons_section_use_label' => $this->reasons_section_use_label,
            'reasons_section_use_image' => $this->reasons_section_use_image,
            'reasons_section_use_description' => $this->reasons_section_use_description,
            'reasons_section_reliable_label' => $this->reasons_section_reliable_label,
            'reasons_section_reliable_image' => $this->reasons_section_reliable_image,
            'reasons_section_reliable_description' => $this->reasons_section_reliable_description,
            'reasons_section_responsible_label' => $this->reasons_section_responsible_label,
            'reasons_section_responsible_image' => $this->reasons_section_responsible_image,
            'reasons_section_responsible_description' => $this->reasons_section_responsible_description,
            'movement_section_heading' => $this->movement_section_heading,
            'movement_section_icon' => $this->movement_section_icon,
            'movement_section_text' => $this->movement_section_text,
            'members_section_heading' => $this->members_section_heading,
            'members_section_text' => $this->members_section_text,
            'news_section_heading' => $this->news_section_heading,
            'news_section_icon1' => $this->news_section_icon1,
            'news_section_icon2' => $this->news_section_icon2,
            'news_section_icon3' => $this->news_section_icon3,
            'news_section_icon4' => $this->news_section_icon4,
            'use_section_heading' => $this->use_section_heading,
            'use_section_text' => $this->use_section_text,
            'use_section_point1_label' => $this->use_section_point1_label,
            'use_section_point1_image' => $this->use_section_point1_image,
            'use_section_point1_description' => $this->use_section_point1_description,
            'use_section_point2_label' => $this->use_section_point2_label,
            'use_section_point2_image' => $this->use_section_point2_image,
            'use_section_point2_description' => $this->use_section_point2_description,
            'use_section_point3_label' => $this->use_section_point3_label,
            'use_section_point3_image' => $this->use_section_point3_image,
            'use_section_point3_description' => $this->use_section_point3_description,
            'use_section_point4_label' => $this->use_section_point4_label,
            'use_section_point4_image' => $this->use_section_point4_image,
            'use_section_point4_description' => $this->use_section_point4_description,
            'reliability_section_heading' => $this->reliability_section_heading,
            'reliability_section_text' => $this->reliability_section_text,
            'reliability_section_passengers_label' => $this->reliability_section_passengers_label,
            'reliability_section_passengers_description' => $this->reliability_section_passengers_description,
            'reliability_section_drivers_label' => $this->reliability_section_drivers_label,
            'reliability_section_drivers_description' => $this->reliability_section_drivers_description,
            'reliability_section_button_label1' => $this->reliability_section_button_label1,
            'reliability_section_button_label2' => $this->reliability_section_button_label2,
            'payment_section_heading' => $this->payment_section_heading,
            'payment_section_text' => $this->payment_section_text,
            'payment_section_icon1' => $this->payment_section_icon1,
            'payment_section_icon2' => $this->payment_section_icon2,
            'payment_section_icon3' => $this->payment_section_icon3,
            'payment_section_icon4' => $this->payment_section_icon4,
            'home_page_setting' => new HomePageSettingResource($this->whenLoaded('homePageSetting')),
            'language' => new LanguageResource($this->whenLoaded('language')),
        ];
    }
}
