<?php

namespace App\Http\Resources\Admin;

use Illuminate\Http\Resources\Json\JsonResource;

class RideDetailPageSettingDetailResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'ride_detail_page_setting_id' => $this->ride_detail_page_id,
            'language_id' => $this->language_id,
            'name' => $this->name,
            'meta_keywords' => $this->meta_keywords,
            'meta_description' => $this->meta_description,
            'main_heading' => $this->main_heading,
            'from_label' => $this->from_label,
            'to_label' => $this->to_label,
            'at_label' => $this->at_label,
            'co_passenger_label' => $this->co_passenger_label,
            'ride_co_passenger_heading' => $this->ride_co_passenger_heading,
            'trip_co_passenger_heading' => $this->trip_co_passenger_heading,
            'payment_method_label' => $this->payment_method_label,
            'booking_type_label' => $this->booking_type_label,
            'cancellation_policy_label' => $this->cancellation_policy_label,
            'luggage_label' => $this->luggage_label,
            'smoking_label' => $this->smoking_label,
            'pets_label' => $this->pets_label,
            'seats_left_label' => $this->seats_left_label,
            'per_seat_label' => $this->per_seat_label,
            'pickup_dropoff_info_heading' => $this->pickup_dropoff_info_heading,
            'pickup_label' => $this->pickup_label,
            'dropoff_label' => $this->dropoff_label,
            'description_label' => $this->description_label,
            'ride_features_label' => $this->ride_features_label,
            'ride_seat_label' => $this->ride_seat_label,
            'all_seats_booked_label' => $this->all_seats_booked_label,
            'ride_canceller_by_driver' => $this->ride_canceller_by_driver,
            'ride_completed_text' => $this->ride_completed_text,
            'book_seat_btn_label' => $this->book_seat_btn_label,
            'no_seat_available_label' => $this->no_seat_available_label,
            'no_ride_found_message' => $this->no_ride_found_message,
            'cancel_booking_btn_label' => $this->cancel_booking_btn_label,
            'cancel_ride_btn_label' => $this->cancel_ride_btn_label,
            'cancel_ride_confirmation' => $this->cancel_ride_confirmation,
            'cancel_ride_yes_btn' => $this->cancel_ride_yes_btn,
            'cancel_ride_no_btn' => $this->cancel_ride_no_btn,
            'edit_ride_btn_label' => $this->edit_ride_btn_label,
            'review_label' => $this->review_label,
            'booking_request_heading' => $this->booking_request_heading,
            'seat_requested_label' => $this->seat_requested_label,
            'request_accept_label' => $this->request_accept_label,
            'request_reject_label' => $this->request_reject_label,
            'secured_cash_heading' => $this->secured_cash_heading,
            'enter_code_label' => $this->enter_code_label,
            'mobile_seat_booked_heading' => $this->mobile_seat_booked_heading,
            'mobile_seat_booked_label' => $this->mobile_seat_booked_label,
            'mobile_seat_fare_label' => $this->mobile_seat_fare_label,
            'mobile_seat_booking_fee_label' => $this->mobile_seat_booking_fee_label,
            'mobile_seat_total_amount_label' => $this->mobile_seat_total_amount_label,
            'vehicle_info_label' => $this->vehicle_info_label,
            'driver_info_label' => $this->driver_info_label,
            'review_driver_info_label' => $this->review_driver_info_label,
            'review_passanger_label' => $this->review_passanger_label,
            'driver_label' => $this->driver_label,
            'cancellation_policy' => $this->cancellation_policy,
            'passengers_driven_label' => $this->passengers_driven_label,
            'driver_age_label' => $this->driver_age_label,
            'driver_chat_heading' => $this->driver_chat_heading,
            'driver_chat_with' => $this->driver_chat_with,
            'driver_chat_label' => $this->driver_chat_label,
            'driver_chat_button_label' => $this->driver_chat_button_label,
            'booking_table_heading' => $this->booking_table_heading,
            'passenger_column_label' => $this->passenger_column_label,
            'seat_booked_column_label' => $this->seat_booked_column_label,
            'total_cost_column_label' => $this->total_cost_column_label,
            'booked_on_column_label' => $this->booked_on_column_label,
            'status_column_label' => $this->status_column_label,
            'booking_requested_status_label' => $this->booking_requested_status_label,
            'seat_booked_status_label' => $this->seat_booked_status_label,
            'booking_denied_status_label' => $this->booking_denied_status_label,
            'actions_column_label' => $this->actions_column_label,
            'edit_button_actions_label' => $this->edit_button_actions_label,
            'review_button_label' => $this->review_button_label,
            'i_reviewed_label' => $this->i_reviewed_label,
            'noon_label' => $this->noon_label,
            'midnight_label' => $this->midnight_label,
            'driver_note_label' => $this->driver_note_label,
            'ride_main_heading' => $this->ride_main_heading,
            'trip_main_heading' => $this->trip_main_heading,
            'discount_label' => $this->discount_label,
            'booking_request_main_heading' => $this->booking_request_main_heading,
            'passenger_age_label' => $this->passenger_age_label,
            'passenger_gender_label' => $this->passenger_gender_label,
            'seat_on_column_label' => $this->seat_on_column_label,
            'cancellation_policy_tooltip' => $this->cancellation_policy_tooltip,
            'cancellation_policy_tooltip_url' => $this->cancellation_policy_tooltip_url,

            'firm_cancellation_confirm_poup_heading' => $this->firm_cancellation_confirm_poup_heading,
            'firm_cancellation_confirm_poup_text' => $this->firm_cancellation_confirm_poup_text,
            'firm_cancellation_confirm_poup_yes_label' => $this->firm_cancellation_confirm_poup_yes_label,
            'firm_cancellation_confirm_poup_no_label' => $this->firm_cancellation_confirm_poup_no_label,
            'chat_error_message' => $this->chat_error_message,
            'empty_chat_placeholder' => $this->empty_chat_placeholder,
            'verified_email' => $this->verified_email,
            'verified_phone' => $this->verified_phone,
            'firm_cancellation_confirm_poup_sub_text' => $this->firm_cancellation_confirm_poup_sub_text,
            'instant_btn_label' => $this->instant_btn_label,

            'ride_detail_page_setting' => new RideDetailPageSettingResource($this->whenLoaded('rideDetailPageSetting')),
            'language' => new LanguageResource($this->whenLoaded('language')),
        ];
    }
}
